spring.application.name=duidui


spring.datasource.url=jdbc:mysql://bt.hutao77.icu:3306/duidui?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=duidui
spring.datasource.password=YB1109ldn
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.id-type=auto